# Generated by Django 3.2 on 2023-08-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonProject3', '0003_trainingwalkstraight_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentcontent',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending')], default='', max_length=20),
        ),
    ]
