# Generated by Django 3.2 on 2023-09-02 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pythonProject3', '0007_remove_trainingdance_friend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingonefoot',
            old_name='time',
            new_name='t_time',
        ),
    ]
