# Generated by Django 3.2 on 2023-09-02 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pythonProject3', '0008_rename_time_trainingonefoot_t_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingonefoot',
            name='friend',
        ),
    ]
