# Generated by Django 3.2 on 2023-09-03 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonProject3', '0010_remove_trainingjump_friend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingjump',
            name='failure_count',
        ),
        migrations.AddField(
            model_name='trainingjump',
            name='t_time',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
