# Generated by Django 3.2 on 2023-09-03 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonProject3', '0011_auto_20230903_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingjump',
            name='grade',
            field=models.CharField(default='none', max_length=1),
        ),
    ]
