# Generated by Django 3.2 on 2023-09-06 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonProject3', '0012_trainingjump_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image_path', models.ImageField(upload_to='background_images/')),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='coins',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
