# Generated by Django 3.2 on 2023-09-06 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonProject3', '0013_auto_20230906_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundimage',
            name='image_path',
            field=models.ImageField(upload_to='background_images'),
        ),
    ]
