# Generated by Django 3.2 on 2023-09-09 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pythonProject3', '0017_alter_trainingjump_t_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingwalkstraight',
            name='friend',
        ),
    ]
