# Generated by Django 3.2 on 2023-09-18 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonProject3', '0018_remove_trainingwalkstraight_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingwalkstraight',
            name='t_time',
            field=models.IntegerField(default=0),
        ),
    ]
