# Generated by Django 3.2 on 2023-09-22 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonProject3', '0022_trainingwalkstraight_t_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_backgroundimage',
            name='image_id',
            field=models.IntegerField(default=0),
        ),
    ]
