# Generated by Django 3.2 on 2023-08-26 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ChildPioneer', '0002_remove_trainingwalkstraight_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingwalkstraight',
            name='friend',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='walkstraight_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
