# Generated by Django 3.2 on 2023-08-28 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChildPioneer', '0005_alter_treatmentcontent_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmentcontent',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending')], default='', max_length=20),
        ),
    ]
