# Generated by Django 3.2 on 2023-09-01 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChildPioneer', '0006_alter_treatmentcontent_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingdance',
            name='friend',
        ),
    ]
