# Generated by Django 3.2 on 2023-09-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChildPioneer', '0016_alter_treatmentcontent_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingjump',
            name='t_time',
            field=models.IntegerField(default=0),
        ),
    ]
