# Generated by Django 3.2 on 2023-09-20 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChildPioneer', '0020_user_backgroundimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingwalkstraight',
            name='t_time',
        ),
    ]
