# Generated by Django 3.2 on 2023-09-20 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChildPioneer', '0021_remove_trainingwalkstraight_t_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingwalkstraight',
            name='t_time',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
