# Generated by Django 5.2 on 2025-04-09 13:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ChildPioneer", "0023_user_backgroundimage_image_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="friends",
            field=models.ManyToManyField(
                blank=True, related_name="user_friends", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="therapists",
            field=models.ManyToManyField(
                blank=True,
                related_name="therapist_friends",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
